### ISSUE TITLE
cannot set properties of undefined

### ISSUE THREAD

**Issue by eleanorkonik** [javalent/obsidian-leaflet#295]
I've been experiencing lag and jerkiness lately and when I check the console, this is one of the errors I see. 

```
Uncaught TypeError: Cannot set properties of undefined (setting '_leaflet_pos')
    at me (eval at <anonymous> (app.js:1:1483483), <anonymous>:2:54194)
    at a._resetView (eval at <anonymous> (app.js:1:1483483), <anonymous>:2:73134)
    at a.setView (eval at <anonymous> (app.js:1:1483483), <anonymous>:2:61436)
    at a.panTo (eval at <anonymous> (app.js:1:1483483), <anonymous>:2:62731)
    at eval (eval at <anonymous> (app.js:1:1483483), <anonymous>:2:1378422)
    at fn.e.tryTrigger (app.js:1:898926)
    at fn.e.trigger (app.js:1:898859)
    at fn.eval (eval at <anonymous> (app.js:1:1483483), <anonymous>:2:1402048)
    at Generator.next (<anonymous>)
    at eval (eval at <anonymous> (app.js:1:1483483), <anonymous>:2:561161)
VM180:115 Folding is off
app.js:1 Uncaught TypeError: Cannot set properties of undefined (setting '_leaflet_pos')
    at me (eval at <anonymous> (app.js:1:1483483), <anonymous>:2:54194)
    at a._resetView (eval at <anonymous> (app.js:1:1483483), <anonymous>:2:73134)
    at a.setView (eval at <anonymous> (app.js:1:1483483), <anonymous>:2:61436)
    at a.panTo (eval at <anonymous> (app.js:1:1483483), <anonymous>:2:62731)
    at eval (eval at <anonymous> (app.js:1:1483483), <anonymous>:2:1378422)
    at fn.e.tryTrigger (app.js:1:898926)
    at fn.e.trigger (app.js:1:898859)
    at fn.eval (eval at <anonymous> (app.js:1:1483483), <anonymous>:2:1402048)
    at Generator.next (<anonymous>)
    at eval (eval at <anonymous> (app.js:1:1483483), <anonymous>:2:561161)
```

**Comment by valentine195** [comment]
What are you doing when this occurs? Just panning?

Can you try two things for me:

1. Add `verbose: true` to the code block
2. Please show me your code block

**Comment by valentine195** [comment]
Is this still occurring?
